COMPILE_FLAGS = -std=c++2a -g -Wall -Wextra

all: demo01 demo02 demo03 demo04 demo05 demo06 demo07 demo08 demo09 demo10 demo11 demo12 demo13

demo01: demo01.cc
	g++ $(COMPILE_FLAGS) -o demo01 demo01.cc -lpthread

demo02: demo02.cc
	g++ $(COMPILE_FLAGS) -o demo02 demo02.cc -lpthread

demo03: demo03.cc
	g++ $(COMPILE_FLAGS) -o demo03 demo03.cc -lpthread

demo04: demo04.cc
	g++ $(COMPILE_FLAGS) -o demo04 demo04.cc -lpthread

demo05: demo05.cc
	g++ $(COMPILE_FLAGS) -o demo05 demo05.cc -lpthread

demo06: demo06.cc
	g++ $(COMPILE_FLAGS) -o demo06 demo06.cc -lpthread

demo07: demo07.cc
	g++ $(COMPILE_FLAGS) -o demo07 demo07.cc -lpthread

demo08: demo08.cc
	g++ $(COMPILE_FLAGS) -o demo08 demo08.cc -lpthread

demo09: demo09.cc
	g++ $(COMPILE_FLAGS) -o demo09 demo09.cc -lpthread

demo10: demo10.cc
	g++ $(COMPILE_FLAGS) -o demo10 demo10.cc -lpthread

demo11: demo11.cc
	g++ $(COMPILE_FLAGS) -o demo11 demo11.cc -lpthread

demo12: demo12.cc
	g++ $(COMPILE_FLAGS) -o demo12 demo12.cc -lpthread

demo13: demo13.cc
	g++ $(COMPILE_FLAGS) -o demo13 demo13.cc -lpthread

clean:
	rm -f demo01 demo02 demo03 demo04 demo05 demo06 demo07 demo08 demo09 demo10 demo11 demo12 demo13
