COMPILE_FLAGS = -std=c++2a -g -Wall -Wextra

all: demo01 demo02 demo03 demo04 demo05 demo06 demo07 demo08 demo10 demo11 demo12\
     demo13 demo14 demo20

demo01: demo01.cc
	g++ $(COMPILE_FLAGS) -o demo01 demo01.cc -lm -lc

demo02: demo02.cc
	g++ $(COMPILE_FLAGS) -o demo02 demo02.cc -lm -lc

demo03: demo03.cc
	g++ $(COMPILE_FLAGS) -o demo03 demo03.cc -lm -lc

demo04: demo04.cc
	g++ $(COMPILE_FLAGS) -o demo04 demo04.cc -lm -lc

demo05: demo05.cc
	g++ $(COMPILE_FLAGS) -o demo05 demo05.cc ../../public/_public.cc -lm -lc

demo06: demo06.cc
	g++ $(COMPILE_FLAGS) -o demo06 demo06.cc ../../public/_public.cc -lm -lc

demo07: demo07.cc
	g++ $(COMPILE_FLAGS) -o demo07 demo07.cc ../../public/_public.cc -lm -lc

demo08: demo08.cc
	g++ $(COMPILE_FLAGS) -o demo08 demo08.cc ../../public/_public.cc -lm -lc

demo10: demo10.cc
	g++ $(COMPILE_FLAGS) -o demo10 demo10.cc ../../public/_public.cc -lm -lc

demo11: demo11.cc
	g++ $(COMPILE_FLAGS) -o demo11 demo11.cc ../../public/_public.cc -lm -lc

demo12: demo12.cc
	g++ $(COMPILE_FLAGS) -o demo12 demo12.cc ../../public/_public.cc -lm -lc

demo13: demo13.cc
	g++ $(COMPILE_FLAGS) -o demo13 demo13.cc ../../public/_public.cc -lm -lc

demo14: demo14.cc
	g++ $(COMPILE_FLAGS) -o demo14 demo14.cc ../../public/_public.cc -lm -lc

demo20: demo20.cc
	g++ $(COMPILE_FLAGS) -o demo20 demo20.cc ../../public/_public.cc -lm -lc

clean:
	rm -f demo01 demo02 demo03 demo04 demo05 demo06 demo07 demo08 demo10 demo11 demo12 demo13 demo14 demo20
